sudo: required
services:
  - docker

before_install:
  - docker build -t ojwag4giec/udktcg-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e "CI=true" ojwag4giec/udktcg-client npm run test -- --coverage

after_success:
  - docker build -t ojwag4giec/udktcg-client ./client
  - docker build -t ojwag4giec/udktcg-nginx ./nginx
  - docker build -t ojwag4giec/udktcg-server ./server
  - docker build -t ojwag4giec/udktcg-worker ./worker

