sudo: required
services:
  - docker

before_install:
  - docker build -t ojwag4giec/udktcg-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e "CI=true" ojwag4giec/udktcg-client npm run test -- --coverage

after_success:
  - docker build -t ojwag4giec/udktcg-client ./client
  - docker build -t ojwag4giec/udktcg-nginx ./nginx
  - docker build -t ojwag4giec/udktcg-server ./server
  - docker build -t ojwag4giec/udktcg-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ojwag4giec/udktcg-client
  - docker push ojwag4giec/udktcg-nginx
  - docker push ojwag4giec/udktcg-server
  - docker push ojwag4giec/udktcg-worker

